set(VCPKG_TARGET_TRIPLET_ARCH x86)
set(VCPKG_TARGET_TRIPLET x86-windows)
set(VCPKG_TARGET_TRIPLET_PLAT "Windows")

set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_HOST_ARCHITECTURE x86)

set(CMAKE_TARGET_ARCHITECTURE x86)
set(CMAKE_HOST_ARCHITECTURE x86)

set(VCPKG_ARCH_ARCHITECTURE x86)

set(CMAKE_ARCH_ARCHITECTURE x86)

set(TARGET_ARCHITECTURE x86)
set(HOST_ARCHITECTURE x86)

set(CMAKE_TARGET_ARCHITECTURE x86)
set(CMAKE_HOST_ARCHITECTURE x86)

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_PLATFORM_TOOLSET v141)
# set(CMAKE_SYSTEM_VERSION 10.0.15063)
set(CMAKE_SYSTEM_VERSION "10.0.17134")

# set(VCPKG_FORTRAN_COMPILER Intel) # Flang, GNU, Intel, PGI
set(VCPKG_FORTRAN_ENABLED ON)
# set(VCPKG_FORTRAN_COMPILER PGI)
set(VCPKG_FORTRAN_COMPILER Intel)
set(VCPKG_FORTRAN_TOOLSET_VERSION 19)

set(INTEL_VERSIONS 19)
set(IFORT_COMPILER 19)
set(CMAKE_Fortran_COMPILER Intel)

set(NINJA_CAN_BE_USED ON) # Ninja as generator
set(NINJA_HOST OFF) # Ninja as parallel configurator
set(ENABLE_PARALLEL OFF)

#set(CMAKE_SYSTEM_NAME "Windows")
#set(CMAKE_SYSTEM_VERSION "10.0.17134")
set(CMAKE_SYSTEM_PROCESSOR x86)
set(VCPKG_CMAKE_SYSTEM_PROCESSOR x86)
set(CMAKE_HOST_SYSTEM_PROCESSOR x86)

set(VCPKG_TARGET_TRIPLET_ARCH x86)
set(CMAKE_GENERATOR_PLATFORM Win32)

set(CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE x86)



#set(CMAKE_CROSSCOMPILING "FALSE")

#set(CMAKE_SYSTEM_LOADED 1)

#set(CMAKE_CXX_COMPILER_ID "MSVC")
#set(CMAKE_CXX_COMPILER_VERSION "19.16.27026.1")


#set(CMAKE_CXX_PLATFORM_ID "Windows")

#set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID X86)
#set(MSVC_CXX_ARCHITECTURE_ID X86)

#set(CMAKE_CXX_COMPILER_LOADED 1)
#set(CMAKE_CXX_COMPILER_WORKS TRUE)
#set(CMAKE_CXX_ABI_COMPILED TRUE)

#set(CMAKE_C_COMPILER_ID "MSVC")
#set(CMAKE_C_COMPILER_VERSION "19.16.27026.1")

#set(CMAKE_C_PLATFORM_ID "Windows")
#set(CMAKE_C_SIMULATE_ID "")
#set(CMAKE_C_SIMULATE_VERSION "")
#set(CMAKE_C_COMPILER_ARCHITECTURE_ID X86)
#set(MSVC_C_ARCHITECTURE_ID X86)

#set(CMAKE_C_COMPILER_LOADED 1)
#set(CMAKE_C_COMPILER_WORKS TRUE)
#set(CMAKE_C_ABI_COMPILED TRUE)