set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

#set(CMAKE_EXE_LINKER_FLAGS /machine:X86)
#set(CMAKE_MODULE_LINKER_FLAGS /machine:X86)
#set(CMAKE_SHARED_LINKER_FLAGS /machine:X86)

set(VCPKG_PLATFORM_TOOLSET v141)

#set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR "x86")
#set(CMAKE_SYSTEM_VERSION 10.0.15063)
set(CMAKE_SYSTEM_VERSION "10.0.17134")

#set(CMAKE_CROSSCOMPILING "FALSE")

#set(CMAKE_SYSTEM_LOADED 1)

#set(CMAKE_CXX_COMPILER_ID "MSVC")
#set(CMAKE_CXX_COMPILER_VERSION "19.16.27026.1")


#set(CMAKE_CXX_PLATFORM_ID "Windows")

#set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID X86)
#set(MSVC_CXX_ARCHITECTURE_ID X86)

#set(CMAKE_CXX_COMPILER_LOADED 1)
#set(CMAKE_CXX_COMPILER_WORKS TRUE)
#set(CMAKE_CXX_ABI_COMPILED TRUE)

#set(CMAKE_C_COMPILER_ID "MSVC")
#set(CMAKE_C_COMPILER_VERSION "19.16.27026.1")

#set(CMAKE_C_PLATFORM_ID "Windows")
#set(CMAKE_C_SIMULATE_ID "")
#set(CMAKE_C_SIMULATE_VERSION "")
#set(CMAKE_C_COMPILER_ARCHITECTURE_ID X86)
#set(MSVC_C_ARCHITECTURE_ID X86)

#set(CMAKE_C_COMPILER_LOADED 1)
#set(CMAKE_C_COMPILER_WORKS TRUE)
#set(CMAKE_C_ABI_COMPILED TRUE)