include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO LukasBanana/LLGL
    REF 8f28437960ed60622e94f4f97b24e842b5a0e9e6
    SHA512 8a6bd4109e977f9def0f04a3d31f7bd4beebbe162c52eaa08a54daf8335871615215ece166e5a9d5b5475b834fd53a26ff9638ff270a2f00c88bab21ed156760
    HEAD_REF master
    PATCHES fix-install-error.patch
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA # Disable this option if project cannot be built with Ninja
    NO_CHARSET_FLAG # automatic templates

    OPTIONS 
      -DGaussLib_DISABLE_AUTO_INIT=OFF 
	  -DGaussLib_ASSERT_EXCEPTION=ON 
	  -DGaussLib_ENABLE_INVERSE_OPERATOR=ON 
	  -DGaussLib_ENABLE_SWIZZLE_OPERATOR=ON 
	  -DGaussLib_ROW_VECTORS=ON
	  -DGaussLib_ROW_MAJOR_STORAGE=ON
      -DGaussLib_REAL_DOUBLE=ON
#      -DGaussLib_INCLUDE_DIR:PATH=${CURRENT_INSTALLED_DIR}/include
      -DLLGL_BUILD_EXAMPLES=OFF
      -DLLGL_BUILD_RENDERER_DIRECT3D11=ON
      -DLLGL_BUILD_RENDERER_DIRECT3D12=OFF
      -DLLGL_BUILD_RENDERER_OPENGL=ON
      -DLLGL_BUILD_RENDERER_VULKAN=OFF
      -DLLGL_BUILD_STATIC_LIB=OFF
      -DLLGL_BUILD_TESTS=OFF
      -DLLGL_BUILD_WRAPPER_CSHARP=OFF
      -DLLGL_ENABLE_CHECKED_CAST=OFF
#      -DLLGL_ENABLE_DEBUG_LAYER=ON
      -DLLGL_ENABLE_JIT_COMPILER=OFF
      -DLLGL_ENABLE_SPIRV_REFLECT=OFF
      -DLLGL_ENABLE_UTILITY=OFF
      -DLLGL_GL_ENABLE_DSA_EXT=ON
      -DLLGL_GL_ENABLE_EXT_PLACEHOLDERS=ON
      -DLLGL_GL_ENABLE_OPENGL2X=OFF
      -DLLGL_GL_ENABLE_VENDOR_EXT=ON
      -DLLGL_GL_INCLUDE_EXTERNAL=ON
      -DLLGL_VK_ENABLE_EXT=OFF
)

vcpkg_install_cmake()

set(VCPKG_POLICY_EMPTY_PACKAGE enabled) # automatic templates
vcpkg_copy_pdbs() # automatic templates
configure_file(${SOURCE_PATH}/LICENSE.txt ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)
###
